### ISSUE TITLE
Signature wrapper missing?

### ISSUE THREAD

**Issue by MrFuNK1** [katosdev/signature#29]
Hi there,

in my test environment I do not have a signature wrapper. Checked the .less and formatting is still there but could not find code that actually create the wrapper.

For my test I did add custom CSS for now to better separate posts from signatures. But just a wild hack. Would be great to have the wrapper back, maybe with some formatting options ;)

Cheers

**Comment by katosdev** [comment]
Hi @MrFuNK1 
My apologies for the delays in coming back to you. Do you have a screenshot of what you’re seeing at present please?

**Comment by katosdev** [comment]
No answer received from issue creator. Closing pending further commentary.
